### ISSUE TITLE
Doesn't save correctly

### ISSUE THREAD

**Issue by McJohnson88** [eriqjaffe/FHM-Rink-Factory#4]
The program only seems to save rink images as generic, unusable files with no extension. Even manually adding an extension like .png doesn't do anything.

**Comment by eriqjaffe** [comment]
The program generates zip files - it's possible your OS is hiding the extension?

**Comment by McJohnson88** [comment]
Oh, yeah, sure enough, clicking the box to view file extensions in File Explorer made it save properly.
